services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
    user: root
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong@Passw0rd"
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./script:/script
    networks:
      - sql_server_network
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools18/bin/sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "YourStrong@Passw0rd",
          "-C",
          "-Q",
          "IF DB_ID('ter_hyperplanning') IS NULL THROW 50000, 'Not ready', 1",
        ]
      interval: 5s
      timeout: 3s
      retries: 10
    command: >
      bash -c "
      /opt/mssql/bin/sqlservr &
      echo 'Waiting for SQL Server...';
      until /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong@Passw0rd' -C -Q 'SELECT 1' &>/dev/null; do
        sleep 2;
      done;
      echo 'Creating Schema...';
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong@Passw0rd' -i /script/init_db.sql -C;
      echo 'Seeding Data...';
      /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'YourStrong@Passw0rd' -i /script/seed_data.sql -C;
      echo 'All scripts executed successfully!';
      wait"

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    depends_on:
      sqlserver:
        condition: service_healthy
    environment:
      ADMINER_DEFAULT_SERVER: sqlserver-db
      ADMINER_DEFAULT_DB: ter_hyperplanning
    ports:
      - "8081:8080"
    networks:
      - sql_server_network

volumes:
  sqlserver_data:

networks:
  sql_server_network:
    driver: bridge
